### ISSUE TITLE
[Feature Request] Text in the middle

### ISSUE THREAD

**Issue by danielgek** [sean-perkins/nativescript-animated-circle#4]
@sean-perkins i was about to make a pr to add this functionality to your plugin, but then i realised the ios pod don't support it.

i did a little search to find a simple pod with the current functionality an support for text(https://github.com/atecle/ATCircularProgressView) 

if it's ok for you i will summit another pr with support for text

thanks!

**Comment by sean-perkins** [comment]
Yeah that's fine, as long as the API remains 1:1 for the end-user.

**Comment by danielgek** [comment]
@sean-perkins thank i will work on it then, and the other pr can wait because i actually need them both xD

**Comment by danielgek** [comment]
@sean-perkins btw do you absolutely need conterClock ?

**Comment by sean-perkins** [comment]
I don't think so, I would bet 95% of implementations only need clockwise animations.

**Comment by danielgek** [comment]
Cool so can i remove that feature(can't find a pod with middle text and conterclock)?

**Comment by danielgek** [comment]
ended up this se same pod xD but added a label as a subview on ios

**Comment by sean-perkins** [comment]
This now should be available with release tag `1.1.0`. Great work!
