### ISSUE TITLE
Demo application crashes

### ISSUE THREAD

**Issue by hanckmann** [sean-perkins/nativescript-animated-circle#7]
Platform: ios emulator
tns --version: 3.4.2

I did a simple git clone, and a "tns run ios".
This results in the following error:
```
$ tns run ios
Searching for devices...
Executing before-prepare hook from /private/tmp/nativescript-animated-circle/demo/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.3.4
Preparing project...
Project successfully prepared (iOS)
Executing after-prepare hook from /private/tmp/nativescript-animated-circle/demo/hooks/after-prepare/nativescript-unit-test-runner.js
Successfully transferred all files.
Refreshing application...
Successfully synced application org.nativescript.demo on device E448BAC2-1F61-4C88-ADC3-C8A7E3DF6E12.
Executing before-watch hook from /private/tmp/nativescript-animated-circle/demo/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.3.4
1   0x1102a86db NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x11097d11e ffi_closure_unix64_inner
3   0x11097da52 ffi_closure_unix64
4   0x1117b69e5 -[UIViewController __viewWillAppear:]
5   0x1117b8242 -[UIViewController viewWillMoveToWindow:]
6   0x1116c0cfd -[UIView(Hierarchy) _willMoveToWindow:withAncestorView:]
7   0x1116d26cd -[UIView(Internal) _addSubview:positioned:relativeTo:]
8   0x11167baa2 -[UIWindow addRootViewControllerViewIfPossible]
9   0x11167bed7 -[UIWindow _setHidden:forced:]
10  0x11168ee54 -[UIWindow makeKeyAndVisible]
11  0x11097d8ad ffi_call_unix64
12  0x1338a2710
file:///app/tns_modules/tns-core-modules/ui/builder/builder.js:196:56: JS ERROR Error: Building UI from XML. @file:///app/main-page.xml:7:7
22:05:46 - Compilation complete. Watching for file changes.
```
I am not sure where to go from here. A working demo/example would really help.

**Comment by pavelDohnalik** [comment]
I have similar problem with `tns run android`

`System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.demo/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: 
System.err: Error: Building UI from XML. @file:///app/main-page.xml:7:7
System.err:  > Module '/data/data/org.nativescript.demo/files/app/nativescript-animated-circle/AnimatedCircle' not found for element 'nativescript-animated-circle/AnimatedCircle:AnimatedCircle'.
System.err:    > com.tns.NativeScriptException: Failed to find module: "/data/data/org.nativescript.demo/files/app/nativescript-animated-circle/AnimatedCircle", relative to: app//
System.err:       com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:953)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:937)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:929)
System.err:     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
System.err:     android.app.Activity.performCreate(Activity.java:7009)
System.err:     android.app.Activity.performCreate(Activity.java:7000)
System.err:     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
System.err:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
System.err:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
System.err:     android.app.ActivityThread.-wrap11(Unknown Source:0)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
System.err:     android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     android.os.Looper.loop(Looper.java:164)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6494)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
System.err: File: "file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 208, column: 20`

**Comment by sean-perkins** [comment]
Please look at the recommended run scripts inside the `src/package.json` file. These will be the same as any plugin using NativeScript's plugin seed: https://github.com/sean-perkins/nativescript-animated-circle/blob/master/src/package.json#L22
