### ISSUE TITLE
Can't resize text

### ISSUE THREAD

**Issue by FranciZ** [sean-perkins/nativescript-animated-circle#9]
### Which platform(s) does your issue occur on?
Android, Pixel XL 2

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.4.2
- Cross-platform modules: 3.4.1
- Runtime(s): tns-android 3.4.2
- Plugin(s):
```
"devDependencies": {
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~1.9.4",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "codelyzer": "~4.0.2",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "1.5.0",
    "nativescript-dev-typescript": "~0.6.0",
    "nativescript-dev-webpack": "~0.9.1",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "tslint": "~5.8.0",
    "typescript": "~2.6.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 

I did a custom layout setup to get around this one but if you use the `text` property on the component I cant change the text size. It's huge and gets clipped.

**Comment by slasho** [comment]
+1

**Comment by alexZaicev** [comment]
I experience the same issue. I have installed the latest version from npm, and the text size is static and cannot be changed by changing textSize property.

Any suggestions on how to fix the issue?

**Comment by Macarthurval** [comment]
I've found the problem, at file animated-circle.android.js , change the line 182:

`this.android.setTextSize(this.textSize);`
by
`this.android.setTextSize(this._textSize);`

After this change you need to do `tns run android --syncAllFiles` to update the file.

**Comment by alexZaicev** [comment]
Thank you that fixed my problem!!! Can this fix be pushed into the plugin, so others would not experience that issue?
